name: docker develop build test and publish

on:
  push:
    branches:
      - main

env:
  registry: docker.io

jobs:
  compute-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Compute develop version
        id: version
        run: |
          DATE_TIME=$(date +"%y.%-m")
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION="${DATE_TIME}-develop-${SHORT_SHA}"
          echo "Build version: $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  docker-build-test:
    needs: compute-version
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.compute-version.outputs.version }}
      push: true
      cache_scope: develop-build
    secrets: inherit

  manifest:
    needs: [compute-version, docker-build-test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: digests-*
          merge-multiple: true
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to ${{ env.registry }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.DOCKER_USER_RW }}
          password: ${{ secrets.DOCKER_PASSWORD_RW }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t "${{ env.registry }}/${{ secrets.DOCKER_ORG }}/besu:develop" \
            $(find /tmp/digests -type f -printf "${{ env.registry }}/${{ secrets.DOCKER_ORG }}/besu@sha256:%f ")
      - name: Inspect manifest
        run: |
          docker buildx imagetools inspect \
            "${{ env.registry }}/${{ secrets.DOCKER_ORG }}/besu:develop"
