name: docker develop build and test only

on:
  pull_request:
    branches:
      - main
      - release-*
      - verkle
      - performance

jobs:
  docker-build-test:
    uses: ./.github/workflows/docker.yml
    with:
      version: dev-pr
      push: false
      cache_scope: develop-pr-build
    secrets: inherit
